version: '3.8'
services:
  java-security:
    image: java-security:latest
    ports:
      - "8000:8000"
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - MYSQL_URL=jdbc:mysql://mysqlserver/java-security
    volumes:
      - ./:/app
    depends_on:
      - mysqlserver
    command: ["./mvnw", "spring-boot:run", "-Dspring-boot.run.profiles=mysql", "-Dspring-boot.run.jvmArguments='-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000'"]

  mysqlserver:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=java-security
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d

  react-app:
    image: node:16
    ports:
      - "3000:3000"
    volumes:
      - ./security-ui:/app
    working_dir: /app
    command: ["npm", "start"]

volumes:
  mysql_data:
  mysql_config:
